# Generated by Django 2.1.7 on 2019-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Registration_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='cehhhh.jpg', upload_to='profile_pics'),
        ),
    ]
