# Generated by Django 2.1.7 on 2019-07-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Registration_App', '0002_auto_20190617_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='profile_pics/cehhhh.jpg', upload_to='profile_pics'),
        ),
    ]
