# Generated by Django 2.1.7 on 2019-05-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0005_auto_20190419_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
